const Aluno = require('./classes/Aluno')
const Turma = require('./classes/Turma')
const TurmaPresencial = require("./classes/TurmaPresencial")

rodrigo = new Aluno({nome: "Rodrigo", login: 12345, ra: 25035})
console.log("\nNome: " + rodrigo.nome)
console.log("Login: " + rodrigo.login)
console.log("RA: " + rodrigo.ra + "\n")

rafael = new Turma({codigo: 4565, nota:8, nome:"Rafael", login:4226, ra: 1252})
console.log("Codigo: " + rafael.codigo)
console.log("Nota: " + rafael.nota)
console.log("Nome: " + rafael.aluno.nome)
console.log("Login: " + rafael.aluno.login)
console.log("RA: " + rafael.aluno.ra)
console.log("Aprovado por nota: " + rafael.aprovado() + "\n")

rodolfo = new TurmaPresencial({codigo: 6588, nota: 4, nome: "Rodolfo", login: 5855, ra:2205, frequencia: 80})
console.log("Codigo: " + rodolfo.codigo)
console.log("Nota: " + rodolfo.nota)
console.log("Nome: " + rodolfo.aluno.nome)
console.log("Login: " + rodolfo.aluno.login)
console.log("RA: " + rodolfo.aluno.ra)
console.log("Frequencia: " + rodolfo.frequencia)
console.log("Aprovado por frequencia: " + rodolfo.aprovado())
console.log("Aprovado por nota: " + rodolfo.constructor.prototype.aprovado() + "\n")